import type { Metadata } from "next";
import "../assets/app.scss";

export const metadata: Metadata = {
  title: "SVMM",
  description: "Generated by Eliso_o",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
